version: '3.8'

services:
  web:
    build: .
    container_name: devsocial_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres_password@db:5432/devsocial_db
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: pgvector/pgvector:pg16
    container_name: devsocial_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: devsocial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devsocial_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: